### ISSUE TITLE
AttributeError: '_thread._local' object has no attribute 'suppress_events'

### ISSUE THREAD

**Issue by 1letter** [bluedynamics/node#18]
I use pas.plugin.ldap in Plone 6 with the following checkouts:

```
yafowil = git https://github.com/conestack/yafowil.git branch=master
yafowil.plone = git git@github.com:bluedynamics/yafowil.plone.git branch=bootstrap-plone6
yafowil.bootstrap = git git@github.com:conestack/yafowil.bootstrap.git branch=2.0
webresource = git https://github.com/conestack/webresource.git branch=master

node.ext.ldap = git https://github.com/conestack/node.ext.ldap.git
node = git https://github.com/conestack/node.git
```

in the last weeks the testsysite is under heavy development, i run the buildout several times a day. i don't have any problems with the ldap stack.

Since today, after buildout, i get an error if the system try to connect the LDAP server.

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 376, in publish_module
  Module ZPublisher.WSGIPublisher, line 271, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module Products.PDBDebugMode.wsgi_runcall, line 60, in pdb_runcall
  Module pas.plugins.ldap.plonecontrolpanel.inspector, line 53, in node_attributes
  Module node.behaviors.attributes, line 64, in attrs
  Module plumber.instructions, line 453, in entrance
  Module node.ext.ldap._node, line 58, in __init__
  Module node.ext.ldap._node, line 100, in load
  Module plumber.instructions, line 453, in entrance
  Module plumber.instructions, line 462, in plumbing
  Module node.ext.ldap._node, line 124, in __setitem__
  Module plumber.instructions, line 453, in entrance
  Module node.behaviors.lifecycle, line 89, in __setitem__
AttributeError: '_thread._local' object has no attribute 'suppress_events'
```

**Comment by rnixx** [comment]
have you updated node to latest master?

**Comment by rnixx** [comment]
https://github.com/conestack/node/blob/master/src/node/behaviors/lifecycle.py#L19

**Comment by 1letter** [comment]
Yes, in the buildout there is the checkout of the master
```
node = git https://github.com/conestack/node.git
```

With an older version of node.ext.ldap and the default node package all is fine.

node.ext.ldap = git https://github.com/conestack/node.ext.ldap.git rev=e09af9fdc1940aa6be72203840fb5b1b5a848328
# node = git https://github.com/conestack/node.git rev=b418904c4e6a1164425da505735ce84f80c5ea6e

**Comment by rnixx** [comment]
have you also updated node.ext.ldap? i doubt that related node.ext.ldap operation runs in another thread. But i might have imlemented the threadlocal stuff the wrong way. please use node and node.ext.ldap pinned to the revisions before the change in lifecycle events. i cannot fix this immediately

**Comment by 1letter** [comment]
like i wrote,  node.ext.ldap is the master checkout and node is the master checkout.

when i use:

* node.ext.ldap = git https://github.com/conestack/node.ext.ldap.git rev=e09af9fdc1940aa6be72203840fb5b1b5a848328

and

* node 1.0 from pypi

all is fine

**Comment by rnixx** [comment]
Hi, can you try again with latest node and node.ext.ldap master please?

**Comment by 1letter** [comment]
Ok, i have tested local and on a staging server, looks good. no errors. Thanks!
